.TH agamBhbt 1 "July 2024" "Version 1.0" "Here is your man"
.SH NAME
agamBhbt \-
       _.-^^---....,,--
   _--                  --_
  <                        >)
  |                         |
   \._                   _./
      ```--. . , ; .--'''
            | |   |
         .-=||  | |=-.
         `-=#$%&%$#=-'
            | ;  :|
   _____.,-#%&$@%#&#~,._____
.SH SYNOPSIS
.B agamBhbt
